# Generated by Django 5.2.7 on 2025-11-04 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='age',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='incident',
            name='bleeding_severity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='bleeding_site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='body_part',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='breathing_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='consciousness',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='flight_no',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='flight_sector',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='frequent_flyer_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='injury_site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='injury_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='onset_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='other_symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pain_severity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='pain_site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='passenger_type',
            field=models.CharField(default='Passenger', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='pulse',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='respiration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='seat_no',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='skin_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='temperature',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
