# Generated by Django 5.2.7 on 2025-11-04 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0002_remove_incident_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='onset_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='age',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='bleeding_severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='bleeding_site',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='breathing_status',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='consciousness',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='flight_no',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='flight_sector',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='frequent_flyer_number',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='injury_site',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='injury_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='other_symptoms',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='pain_severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='pain_site',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='passenger_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='respiration',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='seat_no',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='skin_color',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='temperature',
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='Untitled Incident', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
