# Generated by Django 5.2.7 on 2025-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0003_rename_onset_time_incident_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
